# Generated by Django 4.1.7 on 2023-05-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_page_photo', models.ImageField(upload_to='books')),
                ('hover_image', models.ImageField(upload_to='books')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
