# Generated by Django 4.1.7 on 2023-05-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_products_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
