# Generated by Django 4.1.7 on 2023-05-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_products_discount_products_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='book_description',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
