# Generated by Django 4.1.7 on 2023-05-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_loginform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginForm',
        ),
    ]
