# Generated by Django 4.1.7 on 2023-05-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_delete_loginform'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='book_pdf',
            field=models.FileField(default=1, upload_to='book-pdf'),
            preserve_default=False,
        ),
    ]
