# Generated by Django 4.1.7 on 2023-05-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_products_book_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='book_pdf',
            field=models.FileField(upload_to=None),
        ),
    ]
