# Generated by Django 4.1.7 on 2023-05-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_products_book_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
