# Generated by Django 4.1.7 on 2023-05-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_products_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='author',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
